export enum LoanAccountStates {
  REQUEST_APPROVAL = 'REQUEST_APPROVAL',
  SET_INCOMPLETE = 'SET_INCOMPLETE',
  APPROVE = 'APPROVE',
  UNDO_APPROVE = 'UNDO_APPROVE',
  REJECT = 'REJECT',
  WITHDRAW = 'WITHDRAW',
  CLOSE = 'CLOSE',
  UNDO_REJECT = 'UNDO_REJECT',
  UNDO_WITHDRAW = 'UNDO_WITHDRAW',
  UNDO_CLOSE = 'UNDO_CLOSE',
}
