export enum DepositAccountStates {

PENDING_APPROVAL =	'PENDING_APPROVAL',
APPROVED =	'APPROVED',
ACTIVE =	'ACTIVE',
ACTIVE_IN_ARREARS =	'ACTIVE_IN_ARREARS',
MATURED =	'MATURED',
LOCKED =	'LOCKED',
DORMANT =	'DORMANT',
CLOSED =	'CLOSED',
CLOSED_WRITTEN_OFF =	'CLOSED_WRITTEN_OFF',
WITHDRAWN =	'WITHDRAWN',
CLOSED_REJECTED =	'CLOSED_REJECTED',
}
